const TECNICOS = [
  "SARTORI PABLO FACUNDO",
  "FIONNA LUCAS ISMAEL",
  "OFICINA TECNICA",
  "FAZZI JUAN PABLO",
  "FERNANDEZ OYARZO CRISTIAN MARCELO",
  "MORENO LUIS HERMENEGILDO",
  "CARDENAS OYARZO MANUEL HERNAN",
  "SANTANA ANGEL",
  "GOBBI FABIAN EDGARDO",
  "GODOY GUILLERMO ADOLFO",
  "RODRIGUEZ DIEGO RAUL",
  "ACOSTA TOMAS ALBERTO",
  "MORENO JAVIER ANDRES",
  "ORUÉ HERNÁN"
];
